Feature/empty handshake on windows before burning
LISTENAI/cskburn pull request #4
Opened 2023-02-02 10:14 UTC by listenai-jw

2023-02-02 13:20 UTC, xingrz commented on libcskburn_serial/src/core.c
> +#if defined(_WIN32) || defined(_WIN64)
放到 serial_win32 里做会更好。而且最好定位一下是 CreateFileA 还是 configure_port 起的作用。

2023-02-02 13:22 UTC, xingrz commented
另外，最好squash成同一个提交

2023-02-03 04:21 UTC, listenai-jw commented on libcskburn_serial/src/core.c
> +#if defined(_WIN32) || defined(_WIN64)
已放进serial_win32，另外确定是configure_port起作用（加了个handshake）

2023-02-03 04:22 UTC, listenai-jw commented
> 另外，最好squash成同一个提交

已经squash

2023-02-03 06:54 UTC, xingrz requested changes

2023-02-03 06:54 UTC, xingrz commented on libserial/src/serial_win32.c
> +serial_open_basic(const char *path)
可以叫 `_serial_open`。另外，把声明放在 serial_open 之前，就不需要增加一个头文件了。

2023-02-03 06:54 UTC, xingrz commented on libserial/src/serial_win32.c
> +	free(device_prepare);
serial_close里已经对指针做了free并且把device_prepare赋值为NULL，所以这里不需要free

2023-02-03 07:05 UTC, xingrz approved these changes

2023-02-03 07:06 UTC, xingrz commented
LGTM

2023-02-03 07:06 UTC, merged